### PR TITLE
Add -lntdll

### PR DESCRIPTION
**Pull request by dfalbel**
As per: https://github.com/extendr/extendr/pull/560

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
I suggest you remove R 4.1 since it is already outdated

**Comment by dfalbel** [comment]
You mean from the checks? I guess you still need the -lntdl to be able to build on R4.3 though, right?

**Comment by yutannihilation** [comment]
I think this pull request is not responsible for the failure on R 4.1. Let's fix it in another PR if needed.

So, you can ignore the failure here, but I'm against tweaking the files by hand. I think you can regenerate these by the latest rextendr (and it should be automated ideally).

**Comment by Ilia-Kosenkov** [comment]
The reason it fails for R4.1 is that Rust 1.70 does not work with Rtools 4.2 ore earlier.

**Comment by yutannihilation** [comment]
> Rust 1.70 does not work with Rtools 42

To be precise, it works, but with warnings, which make the CI fail.

**Comment by Ilia-Kosenkov** [comment]
Ok, sounds fair, I'll bypass this and merge PR as is. We need to address the CI issue separately.

**Review by Ilia-Kosenkov — APPROVED** [review]

**Pull request merged**
